### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by noraj** [picatz/chart_js#1]
The last release on rubygems is pretty old, there is a huge difference between git tag v1.0.1.pre and master on `chart_js.rb`.
Can you release version [1.1.0](#3) with all the changes?

**Comment by noraj** [comment]
Right now I cloned the repo and used it with `ruby -Ilib -rchart_js script.rb`

Or edit `lib/chart_js/version.rb` to 1.1.0 and build the gem (`gem build chart_js.gemspec`) and then install it (`gem install chart_js-1.1.0.gem`)

**Comment by picatz** [comment]
👋 Hello @noraj 

Thank you for taking interest in this gem! It's been a while since I've used it, but you're right, the latest non-pre-release is _quite_ old. I will like into updating this. 👍 

For future reference: you can also install [pre-release gems ](https://guides.rubygems.org/patterns/#prerelease-gems)using the `--pre` command-line flag:
```console
$ gem install chart_js --pre
...
```

**Comment by picatz** [comment]
Did some minor updates and released [`1.1.0`](https://rubygems.org/gems/chart_js/versions/1.1.0) with default support for Chart.js [`2.9.3`](https://github.com/chartjs/Chart.js/releases/tag/v2.9.3).

**Comment by picatz** [comment]
**Note:** version 3 seems to be [around the corner](https://github.com/chartjs/Chart.js/blob/b8345173786e072aecd4e6048db6b5eedea69bf0/docs/getting-started/v3-migration.md)?

**Comment by noraj** [comment]
> **Note:** version 3 seems to be [around the corner](https://github.com/chartjs/Chart.js/blob/b8345173786e072aecd4e6048db6b5eedea69bf0/docs/getting-started/v3-migration.md)?

I didn't know about, but yeah seems there are some heavy changes.
